sudo: required
language: python
python:
  - 3.6
env:
  global:
     # Doctr deploy key for teddyrendahl/resume
     - secure: "uJhi8uGccqt/l7BDRX7UNf931zOc4fm6MsJlAxujwv/ASKrzuwFC5O7YDC00EBtav5v0DEJhbZqn6Y9snTPK1Wu+xGy48RJ6NyYF1S32injywjVDM3diY9WCRw7AMwnH8trUYtkHeDTgjgh+CHD1JVOPB3kI7YBffXp6+j7C0ysKIP+OHjalCvufe3HLEUBNoMiRjN7o+yFJijjYKfzhiDCfUDbtkIzg3k/gAuAS+PRg89GaRDk4HBYrexPxoZBYdNJbD7FYMVk9uMIF6gkvo2aZw5CB9tDvEtyE3TL4EH+psPINVXW8AX4kS2cZUWDHQtso6czEJQvasvZ0aSZm/uZ6/4WfWTpMRccNMAJvJHoPIN3htr4T7/IeenJx3RhmQtsUqSNPtLZvPSgO7UzSPIyR8t0HMq1khuWjEGFSZrB/ju2BGjUCyKU1nVDTYsaA6CZ8v7+rpTLj7XVasSL1zgi3DIFMIXZw/GnEcsUwuyq83SjG5qznIMpYfTjKf17UkVFNcOyYs1egIy3aaF4jUffgdXM7wUCGdZSmp5VoZQBo2fkqRKysOi8i0HHRtj8WIjC4suq3rh5mmqJgpOZUZi9f1d2QDyU7G9NlaHozslTNS+/T0RU+aYCS2+Zxhwok+b/T4sc1MYKyw7vdP3joocDSx52/l9/tnqm3ZOLJcpk="

services:
   - docker

before_script:
   - sudo apt-get --purge remove imagemagick
   - sudo apt-get install ghostscript
   - sudo apt-get install libgs-dev
   - sudo apt-get install build-essential libx11-dev libxext-dev zlib1g-dev libpng12-dev libjpeg-dev libfreetype6-dev libxml2-dev
   - sudo apt-get build-dep imagemagick
   - wget https://www.imagemagick.org/download/ImageMagick-7.0.7-28.tar.gz
   - tar -xzvf ImageMagick-7.0.7-28.tar.gz
   - pushd ImageMagick-7.0.7-28 && ./configure --with-gslib=yes --prefix=/usr && make && sudo make install
   - popd

script:
   - docker run --rm -w "/doc" -v "$PWD":/doc thomasweise/texlive make resume.pdf
   - convert -density 300 -quality 90 build/resume.pdf build/resume.png 
   - |
     if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == false ]]; then
       pip install doctr
       doctr deploy --built-docs build --deploy-branch-name build .
     fi
